from focus.core import render_transcript_breakdown_markdown


SERIES_MARKDOWN = """\
# Transcript Page-Number Series — In re M.S-D.

Generated by `pi-skill:recordprep-number-transcript-pages`.

## Summary

| Prefix | Type | File pages | Transcript pages | Collision | Confidence |
|--------|------|------------|------------------|-----------|------------|
| RT     | RT   | 0001–0011  | 1–11             | no        | high       |
| CT     | CT   | 0012–0022  | 8–18             | no        | high       |

## RT — Reporter's Transcript

- **Citation prefix:** `RT`
- **Definition draft:**
  > Reporter's Transcript, **Vol 1**. Cover and index at RT pages 1-3.
- **Rejected false positives:**
  - `0008` contains reporter line numbers, not page numbers.

## Anomalies

1. **`CT-start-offset`** begins at CT page 8.
"""


def _span_texts(
    rendered: str,
    spans: list[tuple[int, int, str]],
    kind: str,
) -> list[str]:
    return [
        rendered[start:end]
        for start, end, span_kind in spans
        if span_kind == kind
    ]


def test_transcript_breakdown_renders_series_markdown_as_native_text() -> None:
    rendered, spans = render_transcript_breakdown_markdown(SERIES_MARKDOWN)

    assert "# Transcript" not in rendered
    assert "| Prefix |" not in rendered
    assert "|--------|" not in rendered
    assert "╭" in rendered
    assert "│ Prefix │ Type │" in rendered
    assert "╰" in rendered
    assert "• Citation prefix: RT" in rendered
    assert "  • 0008 contains reporter line numbers" in rendered
    assert "1. CT-start-offset begins at CT page 8." in rendered
    assert "`" not in rendered

    assert "Transcript Page-Number Series — In re M.S-D." in _span_texts(
        rendered,
        spans,
        "heading1",
    )
    assert "Summary" in _span_texts(rendered, spans, "heading2")
    assert "pi-skill:recordprep-number-transcript-pages" in _span_texts(
        rendered,
        spans,
        "inline_code",
    )
    assert "Reporter's Transcript, Vol 1." in _span_texts(
        rendered,
        spans,
        "blockquote",
    )[0]
    assert "Vol 1" in _span_texts(rendered, spans, "bold")


def test_transcript_breakdown_preserves_literal_html_and_malformed_tables() -> None:
    source = """\
<script>alert("record text")</script>

| A | B |
| not a delimiter |
"""

    rendered, _spans = render_transcript_breakdown_markdown(source)

    assert '<script>alert("record text")</script>' in rendered
    assert "| A | B |" in rendered
    assert "| not a delimiter |" in rendered


def test_transcript_breakdown_styles_fenced_code_without_markers() -> None:
    rendered, spans = render_transcript_breakdown_markdown(
        "```text\ncitation_prefix = RT\n```\n"
    )

    assert rendered == "citation_prefix = RT"
    assert _span_texts(rendered, spans, "code_block") == ["citation_prefix = RT"]
